### ISSUE TITLE
Red tinge on mugwomp93 GBP Overlays

### ISSUE THREAD

**Issue by Bruxism** [mugwomp93/muOS_Customization#3]
![RedTinge_Perfect_GBP-EX_533_nogrid_mugwomp93_ver2_nolight](https://github.com/user-attachments/assets/e0d349ab-e25e-43ef-8559-3914bb4f9bd1)

I love the overlays, but when I was trying out integer sized video output, I noticed a red tinge that really stood out. It seems to appear on all of your GBP overlays.

**Comment by mugwomp93** [comment]
Well that's annoying. Thanks for pointing it out - it should be fixed now.
